name: CI

on: [push, pull_request]

jobs:
  # This job downloads substrate contract node from parity and runs it with the IT
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'paritytech/substrate-contracts-node'
          version: 'tags/v0.16.0'
          file: "substrate-contracts-node-linux.tar.gz"
          target: "node/substrate-contracts-node-linux.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract some files
        run: 7z x node/substrate-contracts-node-linux.tar.gz

      - uses: andstor/file-existence-action@v1
        name: Check file existence
        id: check_files
        with:
          files: "substrate-contracts-node-linux.tar"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo "It exists !"

      - uses: actions/checkout@v2.3.4
      - name: Add Redspot
        run: yarn global add redspot

      - uses: actions/checkout@v2.3.4
      - name: Install
        run: yarn install

      - uses: actions/checkout@v2.3.4
      - name: Format
          run: yarn prettier -w **/*.ts

      - uses: actions/checkout@v2.3.4
      - name: Build
        run: yarn build

